### ISSUE TITLE
Restrict block to only one column with

### ISSUE THREAD

**Issue by MikeHarrison** [rasteiner/conditionalblocks#3]
Hi,

Thanks for putting this together, it is going to be a big help with my projects.

I am trying to restrict a type of block to _only_ one column width. Is this possible? I have this currently:
```yaml
label: Page builder
type: layout
layouts:
  - "1/1"
  - "1/2, 1/2"
  - "1/3, 2/3"
  - "2/3, 1/3"
  - "1/3, 1/3, 1/3"
  - "1/2, 1/6, 1/6, 1/6"
  - "1/6, 1/6, 1/6, 1/2"
  - "1/3, 1/6, 1/6, 1/6, 1/6"
  - "1/6, 1/6, 1/6, 1/6, 1/3"
requires:
  min:
    1/3:
      - text-with-arrow
  max:
    1/3:
      - text-with-arrow
  max:
    1/6:
      - product-link
fieldsets:
  - text-with-arrow
  - product-link
```

To try and make the `text-with-arrow` block only available on the `1/3` width, but it is currently only respecting the `min` setting.

If you have any thoughts that would be super

**Comment by rasteiner** [comment]
It should work like this:

```yml
label: Page builder
type: layout
layouts:
  - "1/1"
  - "1/2, 1/2"
  - "1/3, 2/3"
  - "2/3, 1/3"
  - "1/3, 1/3, 1/3"
  - "1/2, 1/6, 1/6, 1/6"
  - "1/6, 1/6, 1/6, 1/2"
  - "1/3, 1/6, 1/6, 1/6, 1/6"
  - "1/6, 1/6, 1/6, 1/6, 1/3"
requires:
  min:
    1/3:
      - text-with-arrow
  max:
    1/3:
      - text-with-arrow
    1/6:
      - product-link
fieldsets:
  - text-with-arrow
  - product-link
```

(I removed the second `max`).

PS: if you only have 1 block type you want to restrict oer column width, you can skip the array and do it like this:

```yml
label: Page builder
type: layout
layouts:
  - "1/1"
  - "1/2, 1/2"
  - "1/3, 2/3"
  - "2/3, 1/3"
  - "1/3, 1/3, 1/3"
  - "1/2, 1/6, 1/6, 1/6"
  - "1/6, 1/6, 1/6, 1/2"
  - "1/3, 1/6, 1/6, 1/6, 1/6"
  - "1/6, 1/6, 1/6, 1/6, 1/3"
requires:
  min:
    1/3: text-with-arrow
  max:
    1/3: text-with-arrow
    1/6: product-link
fieldsets:
  - text-with-arrow
  - product-link
```
